### ISSUE TITLE
multiple flavors of the nwchem feedstock

### ISSUE THREAD

**Issue by edoapra** [conda-forge/nwchem-feedstock#29] opened 2023-03-17 23:23 UTC
### Comment:

@ltalirz What is the best way for having one NWChem conda package installed with the current defintions and another one with the only change being `ARMCI_TARGET=MPI-PR`  https://nwchemgit.github.io/ARMCI.htm?
`ARMCI_TARGET=MPI-PR` is the recommend settings for multi-nodes runs, but it has the drawback that the mpirun option `-np` requires a value >=2

**Comment by ltalirz** [comment] 2023-03-18 23:05
Hi @edoapra , I don't know whether this is the "best" way, but I suppose you could do something similar to what we do in the cp2k feedstock

https://github.com/conda-forge/cp2k-feedstock/blob/main/recipe/conda_build_config.yaml

you can choose these labels freely and then do different things according to their value in the meta.yaml and also in the build.sh
https://github.com/conda-forge/cp2k-feedstock/blob/f309cdbac574c23c0814c0dc5365acd7b797f555/recipe/build.sh#L14

**Comment by edoapra** [comment] 2023-03-25 02:26
@ltalirz Thanks for tip. I managed to get the MPI-PR variant going.
The only issue I see is that, since the name format given to the conda install files has slightly changed, now we have both the old files (generated a week ago) and the new ones available.  
See https://anaconda.org/conda-forge/nwchem/files
Is this a problem for users?

**Comment by ltalirz** [comment] 2023-03-25 22:50
@edoapra there is one issue in your meta.yaml:

in order for the package prioritization via build number to take effect, you need to use the `build` variable here
https://github.com/conda-forge/nwchem-feedstock/blob/be5fba2d4239a564cd887664531733a8e5d81c96/recipe/meta.yaml#L35

After that, your `mpi_ts` variant now has the highest build numbers and will be installed by default unless users explicitly  request `mamba install -c conda-forge nwchem=*=*mpi_pr*`.

**Comment by edoapra** [comment] 2023-05-19 01:08
@ltalirz I must have got the `build` variable wrong since a generic `conda install -c conda-forge` is pulling the `mpi_pr` variant

```
conda list|grep nwchem
nwchem                    7.2.0            py310_mpi_pr_0    conda-forge
```

**Comment by edoapra** [comment] 2023-05-19 01:17
@ltalirz In as similar fashion, if a execute `conda install -c conda-forge cp2k`, I get the `openmpi_0` version  and not the `nompi_1000` variant ... should we reverse the build value?
```
cp2k               conda-forge/linux-64::cp2k-9.1.0-py39_openmpi_0
```
https://github.com/conda-forge/cp2k-feedstock/commit/2842266aee42b108879169f98ada6ee901e92fdc

**Comment by ltalirz** [comment] 2023-05-20 19:18
Hi @edoapra 

> @ltalirz In as similar fashion, if a execute `conda install -c conda-forge cp2k`, I get the `openmpi_0` version and not the `nompi_1000` variant ...

This is unexpected, and it is not what I find when I install cp2k into a fresh conda environment (if the environment already contains an mpi library perhaps the result may be different; I don't know though exactly what would lead to the behavior you observe)

E.g. this is what I currently get on OSX by default
```
 + cp2k            7.1.0  py38_nompi_1007     conda-forge/osx-64       25MB
```


> @ltalirz I must have got the `build` variable wrong

Yes, if you look closely you are still not actually using different build numbers (it's always 3).
https://github.com/conda-forge/nwchem-feedstock/blob/be5fba2d4239a564cd887664531733a8e5d81c96/recipe/meta.yaml#L35

 See the cp2k recipe for how to change that

**Comment by edoapra** [comment] 2023-05-22 18:04
Here is what I am getting with the attached Dockerfile using an Ubuntu Jammy operating system, after executing the command `DOCKER_BUILDKIT=0  docker build -t  conda_cp2k --file Dockerfile.txt .` 
```
cp2k                      9.1.0            py39_openmpi_0    conda-forge
```
Here is the Dockerfile.txt used [Dockerfile.txt](https://github.com/conda-forge/nwchem-feedstock/files/11534684/Dockerfile.txt)

**Comment by edoapra** [comment] 2023-05-22 22:50
> E.g. this is what I currently get on OSX by default
> 
> ```
>  + cp2k            7.1.0  py38_nompi_1007     conda-forge/osx-64       25MB
> ```

I don't see any `opempi` `osx_64` entry among the cp2k files at https://anaconda.org/conda-forge/cp2k/files, in other words the `openmpi` variant seems to be present only for `linux-64`

**Comment by ltalirz** [comment] 2023-05-22 23:45
hi edoardo, I'm currently super busy and don't have the time to look into it more deeply - what you are showing here indeed appears to indicate that what we are doing in cp2k does not work as intended (apologies)
if you figure out what the problem is or the "right" way of doing it, please let me know; otherwise I'll find some time when things have cooled down a bit

**Comment by edoapra** [comment] 2023-05-23 22:43
Changes from pull request https://github.com/conda-forge/nwchem-feedstock/pull/31 seem to have fixed the package priority both on linux and macos.
I have used a build naming approach that closely resembles what is currently used for the vtk package https://github.com/conda-forge/vtk-feedstock/blob/0e0ead2028a02e98dd0df13b74c3efaa1aaf23aa/recipe/meta.yaml

**Comment by ltalirz** [comment] 2023-05-26 12:24
Interesting...
Do you understand why `py{{ CONDA_PY }}_{{ armci_prefix }}_h{{ PKG_HASH }}_{{ build }}` works but `py{{ CONDA_PY }}_{{ build }}` does not?

Anyhow, thanks for fixing it!

**Closed as completed by ltalirz** 2023-05-26 12:24 UTC
Labels: enhancement, question

**Comment by edoapra** [comment] 2023-05-26 16:34
> Interesting... Do you understand why `py{{ CONDA_PY }}_{{ armci_prefix }}_h{{ PKG_HASH }}_{{ build }}` works but `py{{ CONDA_PY }}_{{ build }}` does not?
> 
> Anyhow, thanks for fixing it!

I am not quite sure how I understand how this conda magic works. The only experimental evidences I have are
1. (micro)mamba seems better at getting the nwchem packages
2. the string build with `PKG_HASH` is much closer to the one that was in place before introducing variants
